# Generated by Django 4.2.7 on 2023-12-02 21:50

from django.db import migrations
from django.contrib.auth import get_user_model
from django.conf import settings

def create_superuser(apps, schema_editor):
    # Get the User model from the apps registry to ensure compatibility
    User = get_user_model()
    # Define the default admin username and email from settings or as a string
    admin_email = getattr(settings, 'DEFAULT_ADMIN_EMAIL', 'admin@example.com')
    admin_password = getattr(settings, 'DEFAULT_ADMIN_PASSWORD', None)
    # Check if a superuser already exists
    if admin_password and not User.objects.filter(email=admin_email).exists():
        # Create a new superuser
        User.objects.create_superuser(
            email=admin_email,
            password=admin_password
        )

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
