image: cs4341/test
registry:
  password: ${ROCKETSHIP_REGISTRY_PASSWORD}
  server: cs4341.azurecr.io
  username: cs4341
service: myapp
github:
  repo: ericmichael/llm-deployment-docker
azure:
  subscription: ${AZURE_SUBSCRIPTION_ID}
  app_service:
    app_name: csci4341-test
    resource_group: cs-rg-4341-scus
    additional_env:
      CHROMADB_STORAGE_PATH: /home/app/db/chromadb/
      DUCKDB_STORAGE_PATH: /home/app/db/duckdb/
      SQLITE3_STORAGE_PATH: /home/app/db/sqlite3/
      WEBSITES_CONTAINER_START_TIME_LIMIT: 500
      WEBSITES_ENABLE_APP_SERVICE_STORAGE: true
      WEBSITES_PORT: 8000
      ENVIRONMENT: production
      DJANGO_STATIC_ROOT: /home/app/staticroot/