name: Deploy to Azure Web App Service (Container)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ROCKETSHIP_REGISTRY_SERVER }}
        username: ${{ secrets.ROCKETSHIP_REGISTRY_USERNAME }}
        password: ${{ secrets.ROCKETSHIP_REGISTRY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.ROCKETSHIP_REGISTRY_SERVER }}/${{ secrets.ROCKETSHIP_IMAGE }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max