name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Build container image
      run: docker build -t registry.digitalocean.com/${{ secrets.REGISTRY_NAME }}/${{ secrets.REPOSITORY_NAME }}:${GITHUB_SHA:0:7} .
    
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200
    
    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/${{ secrets.REGISTRY_NAME }}/${{ secrets.REPOSITORY_NAME }}:${GITHUB_SHA:0:7}
